# ============================================================
# LocalPerks_WEB - Consolidate Database Docs
# Run AFTER cleanup.ps1
# Usage: .\consolidate-db-docs.ps1
# ============================================================

$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
$docsDir = Join-Path $root "docs"

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Consolidating Database Docs" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

if (-not (Test-Path $docsDir)) {
    Write-Host "ERROR: docs\ folder not found. Run cleanup.ps1 first." -ForegroundColor Red
    exit 1
}

# ── Build the consolidated doc ────────────────────────────────
$outputFile = Join-Path $docsDir "DATABASE_COMPLETE_GUIDE.md"

$header = @"
# LocalPerks Database — Complete Guide

> **Single source of truth** for all database setup, configuration, migration, and troubleshooting.
> Generated by consolidate-db-docs.ps1 — $(Get-Date -Format "yyyy-MM-dd")

---

## Table of Contents

1. [Initial Setup](#1-initial-setup)
2. [Environment Configuration](#2-environment-configuration)
3. [Prisma & Accelerate Setup](#3-prisma--accelerate-setup)
4. [Migrations](#4-migrations)
5. [Multi-Database Setup](#5-multi-database-setup)
6. [Production Database](#6-production-database)
7. [Troubleshooting](#7-troubleshooting)

---

"@

# Sections to pull from individual docs (now in docs\)
$sections = [ordered]@{
    "1-initial-setup"           = @("DATABASE_SETUP.md", "CONNECT_TO_MYSQL.md")
    "2-environment-config"      = @("ENVIRONMENT_SETUP.md", "FIX_LOCAL_ENV.md", "FIX_INCOMPLETE_DATABASE_URL.md", "FIX_API_KEY_ERROR.md")
    "3-prisma-accelerate"       = @("SETUP_PRISMA_ACCELERATE.md", "PRISMA_VERCEL_FIX.md")
    "4-migrations"              = @("MIGRATION_INSTRUCTIONS.md", "DATABASE_MIGRATION_INSTRUCTIONS.md")
    "5-multi-database"          = @("MULTI_DATABASE_SETUP.md")
    "6-production"              = @("PRODUCTION_DB_MANUAL_SETUP.md", "DEPLOYMENT_GUIDE.md")
    "7-troubleshooting"         = @("DATABASE_URL_FIX.md", "DATABASE_URL_TROUBLESHOOTING.md", "REDIS_FIX_INSTRUCTIONS.md")
}

$content = $header

foreach ($section in $sections.GetEnumerator()) {
    foreach ($docFile in $section.Value) {
        $docPath = Join-Path $docsDir $docFile
        if (Test-Path $docPath) {
            $fileContent = Get-Content $docPath -Raw
            $content += "`n`n---`n`n<!-- Source: $docFile -->`n`n"
            $content += $fileContent
            Write-Host "   Merged: $docFile" -ForegroundColor Green
        } else {
            Write-Host "   Skipped (not found): $docFile" -ForegroundColor Gray
        }
    }
}

# Write consolidated file
$content | Set-Content -Path $outputFile -Encoding UTF8
Write-Host ""
Write-Host "   Created: docs\DATABASE_COMPLETE_GUIDE.md" -ForegroundColor Cyan

# ── Archive the individual DB docs ────────────────────────────
Write-Host ""
Write-Host "Archiving individual database docs..." -ForegroundColor Yellow

$archiveDir = Join-Path $docsDir "archive"
if (-not (Test-Path $archiveDir)) {
    New-Item -ItemType Directory -Path $archiveDir | Out-Null
}

$dbDocsToArchive = @(
    "DATABASE_SETUP.md",
    "CONNECT_TO_MYSQL.md",
    "DATABASE_MIGRATION_INSTRUCTIONS.md",
    "DATABASE_URL_FIX.md",
    "DATABASE_URL_TROUBLESHOOTING.md",
    "ENVIRONMENT_SETUP.md",
    "ENVIRONMENT_SETUP_COMPLETE.md",
    "FIX_API_KEY_ERROR.md",
    "FIX_INCOMPLETE_DATABASE_URL.md",
    "FIX_LOCAL_ENV.md",
    "LOCAL_ENV_FIXED.md",
    "MIGRATION_INSTRUCTIONS.md",
    "MULTI_DATABASE_SETUP.md",
    "PRISMA_VERCEL_FIX.md",
    "PRODUCTION_DB_MANUAL_SETUP.md",
    "REDIS_FIX_INSTRUCTIONS.md",
    "SETUP_PRISMA_ACCELERATE.md"
)

$archived = 0
foreach ($file in $dbDocsToArchive) {
    $src = Join-Path $docsDir $file
    $dst = Join-Path $archiveDir $file
    if (Test-Path $src) {
        Move-Item -Path $src -Destination $dst -Force
        $archived++
    }
}

Write-Host "   Archived $archived individual docs to docs\archive\" -ForegroundColor Green

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Done! Database docs consolidated." -ForegroundColor Cyan
Write-Host "  See: docs\DATABASE_COMPLETE_GUIDE.md" -ForegroundColor White
Write-Host "  Originals kept in: docs\archive\" -ForegroundColor White
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
